/**
 * wordExport.js — Word (.docx) export module for BuildMetrics
 * Uses docx.js v8 loaded lazily from CDN.
 * Exposes: window.WordExport
 */

const WordExport = (() => {
    const CDN = 'https://cdn.jsdelivr.net/npm/docx@8/build/index.min.js';

    function _loadDocx() {
        return new Promise((resolve, reject) => {
            if (window.docx) { resolve(window.docx); return; }
            const s = document.createElement('script');
            s.src = CDN;
            s.onload = () => resolve(window.docx);
            s.onerror = reject;
            document.head.appendChild(s);
        });
    }

    /**
     * exportBeam(calcData, filename)
     * calcData shape:
     * {
     *   projectName, calcName, date, standard,
     *   inputs:  [{ label, value, unit }],
     *   results: [{ label, value, unit, pass }],
     *   summary: string,
     * }
     */
    async function exportBeam(calcData, filename = 'beam-calculation.docx') {


        const docx = await _loadDocx();
        const {
            Document, Paragraph, TextRun, Table, TableRow, TableCell,
            HeadingLevel, AlignmentType, BorderStyle, WidthType, Packer,
        } = docx;

        const makeHeader = (text, level) => new Paragraph({
            text,
            heading: level,
            spacing: { before: 200, after: 100 },
        });

        const makePara = (text) => new Paragraph({
            children: [new TextRun({ text, size: 22 })],
            spacing: { after: 80 },
        });

        const makeInfoRow = (label, value) => new Paragraph({
            children: [
                new TextRun({ text: label + ': ', bold: true, size: 22 }),
                new TextRun({ text: String(value || '\u2014'), size: 22 }),
            ],
            spacing: { after: 60 },
        });

        const makeTableRow = (cells, isHeader = false) => new TableRow({
            children: cells.map(c => new TableCell({
                children: [new Paragraph({
                    children: [new TextRun({ text: String(c || ''), bold: isHeader, size: 20 })],
                })],
                width: { size: 25, type: WidthType.PERCENTAGE },
            })),
        });

        const inputTable = new Table({
            rows: [
                makeTableRow(['Parameter', 'Value', 'Unit'], true),
                ...(calcData.inputs || []).map(r => makeTableRow([r.label, String(r.value), r.unit || ''])),
            ],
            width: { size: 100, type: WidthType.PERCENTAGE },
        });

        const resultTable = new Table({
            rows: [
                makeTableRow(['Check', 'Value', 'Unit', 'Status'], true),
                ...(calcData.results || []).map(r => makeTableRow([
                    r.label,
                    String(r.value),
                    r.unit || '',
                    r.pass === true ? 'PASS' : r.pass === false ? 'FAIL' : '\u2014',
                ])),
            ],
            width: { size: 100, type: WidthType.PERCENTAGE },
        });

        const doc = new Document({
            sections: [{
                children: [
                    makeHeader('BuildMetrics \u2014 Structural Calculation', HeadingLevel.HEADING_1),
                    makeInfoRow('Project', calcData.projectName),
                    makeInfoRow('Calculation', calcData.calcName),
                    makeInfoRow('Date', calcData.date || new Date().toLocaleDateString()),
                    makeInfoRow('Standard', calcData.standard),
                    makeHeader('Inputs', HeadingLevel.HEADING_2),
                    inputTable,
                    new Paragraph({ text: '', spacing: { after: 200 } }),
                    makeHeader('Results', HeadingLevel.HEADING_2),
                    resultTable,
                    new Paragraph({ text: '', spacing: { after: 200 } }),
                    makeHeader('Summary', HeadingLevel.HEADING_2),
                    makePara(calcData.summary || ''),
                    new Paragraph({ text: '', spacing: { after: 400 } }),
                    makePara('Generated by BuildMetrics \u2014 buildmetrics.uk'),
                ],
            }],
        });

        const blob = await Packer.toBlob(doc);
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        a.click();
        URL.revokeObjectURL(url);
    }

    return { exportBeam };
})();

window.WordExport = WordExport;
